
root: ./

​structure:  
    readme: README.md  
    summary: SUMMARY.md​

redirects:  

    how-to/:                                             content/how-to/README.md 
    how-to/django-admin-customization/:                  content/how-to/django-admin-customization.md 
    how-to/django-chart-example/:                        content/how-to/django-chart-example.md
    how-to/django-deploy-on-heroku/:                     content/how-to/django-deploy-on-heroku.md
    how-to/flask-apache-centos-virtualenv-minimal-configuration/:  content/how-to/flask-apache-centos-virtualenv-minimal-configuration.md
    how-to/flask-code-simple-app/:                       content/how-to/flask-code-simple-app.md
    how-to/flask-deploy-on-heroku/:                      content/how-to/flask-deploy-on-heroku.md
    how-to/flask-structure-your-project/:                content/how-to/flask-structure-your-project.md
    how-to/getting-started-with-python/:                 content/how-to/getting-started-with-python.md
    how-to/install-flask/:                               content/how-to/install-flask.md
    how-to/install-python/:                              content/how-to/install-python.md
    how-to/install-python38-ubuntu/:                     content/how-to/install-python38-ubuntu.md
    how-to/python-crawl-website/:                        content/how-to/python-crawl-website.md
    how-to/setup-centos-for-development/:                content/how-to/setup-centos-for-development.md
    how-to/setup-ubuntu-for-development/:                content/how-to/setup-ubuntu-for-development.md
    how-to/setup-windows-for-development/:               content/how-to/setup-windows-for-development.md

    what-is/:                                            content/what-is/README.md 
    what-is/boilerplate-code/:                           content/what-is/boilerplate-code.md 
    what-is/bulma-css/:                                  content/what-is/bulma-css.md 
    what-is/centos/:                                     content/what-is/centos.md 
    what-is/django/:                                     content/what-is/django.md 
    what-is/eleventy/:                                   content/what-is/eleventy.md 
    what-is/flask/:                                      content/what-is/flask.md 
    what-is/gunicorn/:                                   content/what-is/gunicorn.md 
    what-is/heroku/:                                     content/what-is/heroku.md 
    what-is/jamstack/:                                   content/what-is/jamstack.md 
    what-is/jinja/:                                      content/what-is/jinja.md 
    what-is/nginx/:                                      content/what-is/nginx.md 
    what-is/n-tier-architecture/:                        content/what-is/n-tier-architecture.md 
    what-is/panini/:                                     content/what-is/panini.md 
    what-is/pipenv/:                                     content/what-is/pipenv.md 
    what-is/python/:                                     content/what-is/python.md 
    what-is/single-tier-architecture/:                   content/what-is/single-tier-architecture.md 
    what-is/static-site/:                                content/what-is/static-site.md 
    what-is/svelte-js/:                                  content/what-is/svelte-js.md 
    what-is/two-tier-architecture/:                      content/what-is/two-tier-architecture.md 
    what-is/ubuntu/:                                     content/what-is/ubuntu.md 
    what-is/uwsgi/:                                      content/what-is/uwsgi.md 
    what-is/wsgi/:                                       content/what-is/wsgi.md 

    tutorials/:                                              content/tutorials/README.md
    tutorials/flask-understand-flask-code-simple-app/:       content/tutorials/flask-code-simple-web-app.md

    bootstrap-template/:                                     content/bootstrap-template/README.md
    bootstrap-template/argon-dashboard/:                     content/bootstrap-template/argon-dashboard.md
    bootstrap-template/argon-dashboard-pro/:                 content/bootstrap-template/argon-dashboard-pro.md
    bootstrap-template/atlantis-lite/:                       content/bootstrap-template/atlantis-lite.md
    bootstrap-template/azia-dashboard-pro/:                  content/bootstrap-template/azia-dashboard-pro.md
    bootstrap-template/black-dashboard/:                     content/bootstrap-template/black-dashboard.md
    bootstrap-template/black-dashboard-pro/:                 content/bootstrap-template/black-dashboard-pro.md
    bootstrap-template/datta-able/:                          content/bootstrap-template/datta-able.md
    bootstrap-template/datta-able-pro/:                      content/bootstrap-template/datta-able-pro.md
    bootstrap-template/light-bootstrap-dashboard/:           content/bootstrap-template/light-bootstrap-dashboard.md
    bootstrap-template/material-dashboard/:                  content/bootstrap-template/material-dashboard.md
    bootstrap-template/pixel-lite-template/:                 content/bootstrap-template/pixel-lite-template.md
    bootstrap-template/pixel-pro/:                           content/bootstrap-template/pixel-pro.md
    bootstrap-template/tabler/:                              content/bootstrap-template/tabler.md
    bootstrap-template/volt-dashboard/:                      content/bootstrap-template/volt-dashboard.md

    admin-dashboards/flask-dashboard-atlantis-dark/:         products/flask-dashboards/atlantis-dark.md
    admin-dashboards/flask-dashboard-atlantis-dark-pro/:     products/flask-dashboards/atlantis-dark-pro.md
    admin-dashboards/flask-dashboard-argon/:                 products/flask-dashboards/argon-dashboard.md
    admin-dashboards/flask-dashboard-black/:                 products/flask-dashboards/black-dashboard.md
    admin-dashboards/flask-dashboard-dattaable/:             products/flask-dashboards/datta-able.md
    admin-dashboards/flask-dashboard-dattaable-pro/:         products/flask-dashboards/datta-able-pro.md
    admin-dashboards/flask-dashboard-adminlte/:              products/flask-dashboards/adminlte.md
    admin-dashboards/flask-dashboard-material/:              products/flask-dashboards/material-dashboard.md
    admin-dashboards/flask-material-dashboard-wpx-pro/:      products/flask-dashboards/materialpro-wpx.md 
    admin-dashboards/flask-dashboard-volt/:                  products/flask-dashboards/volt.md
    admin-dashboards/flask-dashboard-volt-pro/:              products/flask-dashboards/volt-pro.md
    admin-dashboards/flask-dashboard-coreui/:                products/flask-dashboards/coreui.md

    admin-dashboards/django-dashboard-atlantis-dark/:        products/django-dashboards/atlantis-dark.md
    admin-dashboards/django-dashboard-atlantis-dark-pro/:    products/django-dashboards/atlantis-dark-pro.md
    admin-dashboards/django-dashboard-argon/:                products/django-dashboards/argon-dashboard.md
    admin-dashboards/django-dashboard-black/:                products/django-dashboards/black-dashboard.md
    admin-dashboards/django-dashboard-dattaable/:            products/django-dashboards/datta-able.md
    admin-dashboards/django-dashboard-dattaable-pro/:        products/django-dashboards/datta-able-pro.md
    admin-dashboards/django-dashboard-adminlte/:             products/django-dashboards/adminlte.md
    admin-dashboards/django-dashboard-material/:             products/django-dashboards/material-dashboard.md
    admin-dashboards/django-material-dashboard-wpx-pro/:     products/django-dashboards/materialpro-wpx.md 
    admin-dashboards/django-dashboard-volt/:                 products/django-dashboards/volt.md
    admin-dashboards/django-dashboard-volt-pro/:             products/django-dashboards/volt-pro.md
    admin-dashboards/django-dashboard-coreui/:               products/django-dashboards/coreui.md
