
root: ./

​structure:  
    readme: README.md  
    summary: SUMMARY.md​

redirects:
    what-is: content/what-is/README.md
    what-is/: content/what-is/README.md
    what-is/flask: content/what-is/flask.md
    what-is/flask/: content/what-is/flask.md
    what-is/django: content/what-is/django.md
    what-is/django/: content/what-is/django.md
    how-to: content/how-to/README.md
    how-to/: content/how-to/README.md
    admin-dashboards: boilerplate-code/django-dashboard.md
    admin-dashboards/: boilerplate-code/django-dashboard.md
    apps/react: products/react/README.md
    apps/react/: products/react/README.md
    how-to/django-admin-customization: content/how-to/django-admin-customization.md
    how-to/django-admin-customization/: content/how-to/django-admin-customization.md
    how-to/django-chart-example: content/how-to/django-chart-example.md
    how-to/django-chart-example/: content/how-to/django-chart-example.md
    how-to/django-deploy-on-heroku: content/how-to/django-deploy-on-heroku.md
    how-to/django-deploy-on-heroku/: content/how-to/django-deploy-on-heroku.md
    how-to/flask-apache-centos-virtualenv-minimal-configuration: content/how-to/flask-apache-centos-virtualenv-minimal-configuration.md
    how-to/flask-apache-centos-virtualenv-minimal-configuration/: content/how-to/flask-apache-centos-virtualenv-minimal-configuration.md
    how-to/flask-code-simple-app: content/how-to/flask-code-simple-app.md
    how-to/flask-code-simple-app/: content/how-to/flask-code-simple-app.md
    how-to/flask-deploy-on-heroku: content/how-to/flask-deploy-on-heroku.md
    how-to/flask-deploy-on-heroku/: content/how-to/flask-deploy-on-heroku.md
    how-to/flask-structure-your-project: content/how-to/flask-structure-your-project.md
    how-to/flask-structure-your-project/: content/how-to/flask-structure-your-project.md
    how-to/getting-started-with-python: content/how-to/getting-started-with-python.md
    how-to/getting-started-with-python/: content/how-to/getting-started-with-python.md
    how-to/install-flask: content/how-to/install-flask.md
    how-to/install-flask/: content/how-to/install-flask.md
    how-to/install-python: content/how-to/install-python.md
    how-to/install-python/: content/how-to/install-python.md
    how-to/install-python38-ubuntu: content/how-to/install-python38-ubuntu.md
    how-to/install-python38-ubuntu/: content/how-to/install-python38-ubuntu.md
    how-to/python-crawl-website: content/how-to/python-crawl-website.md
    how-to/python-crawl-website/: content/how-to/python-crawl-website.md
    how-to/setup-centos-for-development: content/how-to/setup-centos-for-development.md
    how-to/setup-centos-for-development/: content/how-to/setup-centos-for-development.md
    how-to/setup-ubuntu-for-development: content/how-to/setup-ubuntu-for-development.md
    how-to/setup-ubuntu-for-development/: content/how-to/setup-ubuntu-for-development.md
    how-to/setup-windows-for-development: content/how-to/setup-windows-for-development.md
    how-to/setup-windows-for-development/: content/how-to/setup-windows-for-development.md
