
root: ./

​structure:  
    readme: README.md  
    summary: SUMMARY.md​

redirects:  
    bootstrap-template/argon-dashboard:          content/bootstrap-template/argon-dashboard.md

    admin-dashboards/flask-dashboard-black:      products/flask-dashboards/black-dashboard.md
    admin-dashboards/flask-dashboard-dattaable:  products/flask-dashboards/datta-able.md
    
    admin-dashboards/django-dashboard-black:     products/django-dashboards/black-dashboard.md
    admin-dashboards/django-dashboard-dattaable: products/django-dashboards/datta-able.md

